### ISSUE TITLE
Reference for suspension modeling can be added as a PDF.

### ISSUE THREAD

**Issue by imsenthur** [spider-tronix/shadow-bot#1]
It would be better if you (@jaxxstar) can convert the .docx to a .pdf file.

**Comment by jaxxstar** [comment]
The .docx file was not there in the repo at first. Just check whether I have added the correct file.

**Comment by imsenthur** [comment]
PATH: source/suspensionModeling.docx

**Comment by imsenthur** [comment]
PATH: source/suspensionModeling.docx can be deleted then.
